### ISSUE TITLE
Compatibility with rasa NLU v0.9x

### ISSUE THREAD

**Issue by rebeca1987** [sohlex/botkit-rasa#1]
Hi, it seems that there is some problems when using this middleware with rasa NLU >0.7
Whenever you interact with the rasa server, the following error appears: 

`Unhandled rejection StatusCodeError: 404 - {"error":"Invalid parse parameter specified"}`

This error appears after calling the nodeJS program with:
`slack_token=XXXXX node bot.js`

Rasa is installed using pip, and botkit using npm after cloning the main repository.

Kind regards

LOG
```
Initializing Botkit v0.5.4
info: ** No persistent storage method specified! Data may be lost when process shuts down.
debug: Setting up a handler for spawned
debug: Setting up a handler for heard_trigger
debug: Setting up a handler for command_triggered
debug: Setting up a handler for remote_command_end
info: ** Setting up custom handlers for processing Slack messages
debug: Setting up a handler for message_received
debug: rtm.connect { token: 'XXXXX' }
info: ** API CALL: https://slack.com/api/rtm.connect
{ receive: [Function: receive], hears: [Function: hears] }
debug: Setting up a handler for direct_message
debug: Setting up a handler for direct_mention
debug: Setting up a handler for mention
debug: Got response null {"ok":true,"url":"wss:\/\/mpmulti-s1ou.slack-msgs.com\/websocketXXXXXXXXXXX=","team":{"id":"XXXXXXXXXX","name":"Slack test","domain":"XXXX-test"},"self":{"id":"U5W5ZP7HC","name":"XXXX-test-bot"}}
notice: ** BOT ID: XXXXXXXXXX-bot ...attempting to connect to RTM!
notice: RTM websocket opened
Unhandled rejection StatusCodeError: 404 - {"error":"Invalid parse parameter specified"}
    at new StatusCodeError (~/example/test_rasa_nlu/botkit-rasa/node_modules/request-promise-core/lib/errors.js:32:15)
    at Request.plumbing.callback (~/example/test_rasa_nlu/botkit-rasa/node_modules/request-promise-core/lib/plumbing.js:104:33)
    at Request.RP$callback [as _callback] (~/example/test_rasa_nlu/botkit-rasa/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at Request.self.callback (~/example/test_rasa_nlu/botkit-rasa/node_modules/request/request.js:188:22)
    at emitTwo (events.js:125:13)
    at Request.emit (events.js:213:7)
    at Request.<anonymous> (~/example/test_rasa_nlu/botkit-rasa/node_modules/request/request.js:1171:10)
    at emitOne (events.js:115:13)
    at Request.emit (events.js:210:7)
    at IncomingMessage.<anonymous> (~/example/test_rasa_nlu/botkit-rasa/node_modules/request/request.js:1091:12)
    at Object.onceWrapper (events.js:312:19)
    at emitNone (events.js:110:20)
    at IncomingMessage.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1045:12)
    at _combinedTickCallback (internal/process/next_tick.js:102:11)
    at process._tickCallback (internal/process/next_tick.js:161:9)

Unhandled rejection StatusCodeError: 404 - {"error":"Invalid parse parameter specified"}
    at new StatusCodeError (~/example/test_rasa_nlu/botkit-rasa/node_modules/request-promise-core/lib/errors.js:32:15)
    at Request.plumbing.callback (~/example/test_rasa_nlu/botkit-rasa/node_modules/request-promise-core/lib/plumbing.js:104:33)
    at Request.RP$callback [as _callback] (~/example/test_rasa_nlu/botkit-rasa/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at Request.self.callback (~/example/test_rasa_nlu/botkit-rasa/node_modules/request/request.js:188:22)
    at emitTwo (events.js:125:13)
    at Request.emit (events.js:213:7)
    at Request.<anonymous> (~/example/test_rasa_nlu/botkit-rasa/node_modules/request/request.js:1171:10)
    at emitOne (events.js:115:13)
    at Request.emit (events.js:210:7)
```

**Comment by fgr1986** [comment]
Hi, I think that can be solved by checking the message to be passed to Rasa. Changing
  `if (message.is_echo) {`
to
`  if (message.is_echo || message.type != 'message') {`
kind of solves the issue.

**Comment by fgr1986** [comment]
Hi again.
To work with rasa 0.9 (latest at this moment) also the request handler should be changed:

Tried to commit to the repo, but had no rights to.

```
request(options).then(response => {
          // Standard rasa response
          //   {
          //     "text": "I am looking for Chinese food",
          //     "entities": [
          //         {
          //           "start": 8,
          //           "end": 15,
          //           "value": "chinese",
          //           "entity": "cuisine"
          //         }
          //     ],
          //     "intent": {
          //         "confidence": 0.6485910906220309,
          //         "name": "restaurant_search"
          //     },
          //     "intent_ranking": [
          //         {
          //             "confidence": 0.6485910906220309,
          //             "name": "restaurant_search"
          //         },
          //         {
          //             "confidence": 0.14161531595656784,
          //             "name": "affirm"
          //         }
          //     ]
          // }
          // @TODO: The check for confidence should be done in the middleware and not after.
          console.log('\t[own_debug]  Rasa response', response)
          message.intent = response.intent.name
          message.confidence = response.intent.confidence
          message.entities = response.entities
          console.log('\t[own_debug]  intent:', message.intent)
          console.log('\t[own_debug]  entities:', message.entities)
          console.log('\t[own_debug]  confidence:', message.confidence)
          next()
        })
```

**Comment by sohlex** [comment]
Hi all!
Please try the latest version of the npm package (1.0.3 at the moment), all the problems should be solved. The only thing is that you must run your Rasa instance and not the docker image in the example. I'll update the docs asap.

The problems where:

1. if the bot platforms sends us a message without any text, we will send a bad request to Rasa (as spotted by @fgr1986 in his first comment)
2. I was relying on an old version of Rasa, with the old payload. Sorry about that, i fixed it (in a slightly different way then the one suggested by @fgr1986, the confidence is wrapped in the intent object and is not a single property anymore)

Please tell me if everything works as expected and thank you for reporting!

**Comment by fgr1986** [comment]
Perfect, that solves the issue!

THanks!

**Comment by vikash044** [comment]
hi all !
i facing such as problem any solution ? (http://localhost:5000/parse)


{
  "error": "Invalid parse parameter specified"
}

**Comment by vikash044** [comment]
and also ?(http://localhost:5000/parse?q=hello%20there)

{
  "project": "default", 
  "entities": [], 
  "intent": {
    "confidence": 0.6852470563023119, 
    "name": "greet"
  }, 
  "text": "hello there", 
  "model": "model_20181026-123523", 
  "intent_ranking": [
    {
      "confidence": 0.6852470563023119, 
      "name": "greet"
    }, 
    {
      "confidence": 0.1782927244349375, 
      "name": "affirm"
    }, 
    {
      "confidence": 0.07256601013379048, 
      "name": "thank"
    }, 
    {
      "confidence": 0.04439257040932929, 
      "name": "bye"
    }, 
    {
      "confidence": 0.011187696661811092, 
      "name": "name"
    }, 
    {
      "confidence": 0.008313942057819792, 
      "name": "joke"
    }
  ]
}
